title: Settings
data:
  logo: brand/logo3.png
  hero_image: hero/pexels-fauxels-3183199.jpg
  cta_text: 'Start her'
  cta_link: home
  tagline: 'Webudvikling og design'
  copyright: '&copy 2025 Detailservice'
